### ISSUE TITLE
Epic gear captured as Edic

### ISSUE THREAD

**Issue by trolololsaurus** [compeanansi/epic7#15]
As above.

Some Epic gear get captured as Edic

![Capture](https://user-images.githubusercontent.com/45089996/98702296-2ca51080-23b5-11eb-871a-b82d1d3844cb.PNG)

**Comment by wsauret** [comment]
Yeah, this is a known problem with Tesseract OCR. What is confusing me is why that value is not getting replaced post-processing since I have a `.replace('Edic','Epic')` in the script. Would it be possible for you to pinpoint which screenshot was being misrecognized (open the json itself, search for edic, look at the substats, then find the screenshot with those subs) so I can test it myself?

**Comment by trolololsaurus** [comment]
I took some time to dig through the JSON and match my screenshots.
It should be this one

{"locked": false, "efficiency": 0, "rarity": "Edic", "slot": "Ring", "level": 78, "ability": 12, "mainStat": ["HPP", 43], "subStat1": ["Eff", 13], "subStat2": ["Spd", 6], "subStat3": ["CChance", 8], "subStat4": ["Res", 12], "set": "Resist", "id": "jt16sr9s"},

![Screenshot_20201111-001020](https://user-images.githubusercontent.com/45089996/98774390-e1771600-2425-11eb-8a8d-cb342d3bf26d.png)

**Comment by wsauret** [comment]
Ok I'll try processing it locally to see if I can (a) replicate the error, and (b) figure out where the problem in the script is that allowed that mistake to slip through.
